name: Update FreeIPTV Credentials

on:

  workflow_dispatch:

  schedule:

    # 05:00 Lithuania (summer UTC+3)
    - cron: "0 2 * * *"

    # 05:00 Lithuania (winter UTC+2)
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update credentials
        env:
          TWOCAPTCHA_API_KEY: ${{ secrets.TWOCAPTCHA_API_KEY }}
        run: |
          python update_credentials.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add languages/lit.m3u

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update FreeIPTV credentials"
            git push
          fi